// .assets/angular/components/BasicSelect/BasicSelect.component.ts
import { Component, Input, booleanAttribute, numberAttribute } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  standalone: true,
  selector: 'app-basic-select',
  imports: [CommonModule, FormsModule],
  templateUrl: './BasicSelect.component.html',
  styleUrl: './BasicSelect.component.scss'
})
export class BasicSelectComponent {
  @Input() selectWrapperClass: string = '';

  @Input() selectLabelClass: string = '';
  @Input({ required: true }) selectLabel!: string;

  @Input() selectClass: string = '';
  @Input({ required: true }) selectId!: string;
  @Input({ required: true }) selectName!: string;
  @Input() selectForm: string = '';
  @Input({ transform: parseOptions }) selectOptions: Option[] = [];
  @Input({ transform: parseOptionsGroup }) selectOptionsGroup: OptionsGroup[] = [];
  @Input() selectAutocomplete: string = '';
  @Input({ transform: booleanAttribute }) selectAutofocus: boolean = false;
  @Input({ transform: booleanAttribute }) selectDisabled: boolean = false;
  @Input() selectValue: string = '';
  @Input({ transform: booleanAttribute }) selectMultiple: boolean = false;
  @Input({ transform: booleanAttribute }) selectRequired: boolean = false;
  @Input({ transform: numberAttribute }) selectSize!: number;
}

interface OptionsGroup {
  label: string;
  disabled?: boolean;
  options: Option[];
}
interface Option {
  label: string;
  value: string;
  disabled?: boolean;
  selected?: boolean;
}
function parseOptions(object: string): Option[] {
  return JSON.parse(object)
}
function parseOptionsGroup(object: string): OptionsGroup[] {
  return JSON.parse(object)
}
<div class="basic-select {{ selectWrapperClass }}">
    <label for="{{ selectName }}"
        class="{{ selectLabelClass }}">
        {{ selectLabel }}
    </label>

    <select
        class="{{ selectClass }}"
        id="{{ selectId }}"
        name="{{ selectName }}"
        [attr.autocomplete]="selectAutocomplete ? selectAutocomplete : null"
        [attr.autofocus]="selectAutofocus ? selectAutofocus : null"
        [attr.disabled]="selectDisabled ? selectDisabled : null"
        [attr.form]="selectForm"
        [attr.multiple]="selectMultiple ? selectMultiple : null"
        [attr.required]="selectRequired ? selectRequired: null"
        [attr.size]="selectSize ? selectSize : null"
        value="{{ selectValue }}"
        [(ngModel)]="selectValue"
    >
        <ng-container *ngIf="selectOptions.length">
            <option *ngFor="let option of selectOptions"
                disabled="{{ option.disabled ? option.disabled : null }}"
                selected="{{ option.selected ? option.selected : null }}"
                value="{{ option.value }}">
                {{ option.label }}
            </option>
        </ng-container>

        <ng-container *ngIf="selectOptionsGroup.length">
            <optgroup *ngFor="let optionGroup of selectOptionsGroup"
                disabled="{{ optionGroup.disabled ? optionGroup.disabled : null }}"
                label="{{ optionGroup.label }}">
                <option *ngFor="let option of optionGroup.options"
                    disabled="{{ option.disabled ? option.disabled : null }}"
                    selected="{{ option.selected ? option.selected : null }}"
                    value="{{ option.value }}">
                    {{ option.label }}
                </option>
            </optgroup>
        </ng-container>
    </select>
</div>

// .assets/vue/components/BasicSelect.vue
<template>
    <div class="basic-select" :class="selectWrapperClass">
        <label :for="selectName">{{ selectLabel }}</label>
        <select
            :class="selectClass"
            :id="selectName"
            :name="selectName"
            :autocomplete="selectAutocomplete"
            :autofocus="selectAutofocus"
            :disabled="selectDisabled"
            :form="selectForm"
            :multiple="selectMultiple"
            :required="selectRequired"
            :size="selectSize"
            :value="selectValue"
        >
            <template v-if="selectOptions">
                <BasicOption :optionList="selectOptions" />
            </template>
            <template v-if="selectOptionsGroup">
                <optgroup
                    v-for="(optionGroup, index) of selectOptionsGroup"
                    :key="index"
                    :disabled="optionGroup.disabled"
                    :label="optionGroup.label"
                >
                    <BasicOption :optionList="optionGroup.options" />
                </optgroup>
            </template>
        </select>
    </div>
</template>

<script lang="ts">
import { type PropType, defineComponent } from "vue";
import BasicOption from "./BasicOption.vue";

interface Option {
    label: string;
    value: string;
    disabled?: boolean;
    selected?: boolean;
}

interface OptionGroup {
    label: string;
    disabled?: boolean;
    options: Option[];
}

export default defineComponent({
    name: "BasicSelect",
    components: { BasicOption },
    props: {
        selectWrapperClass: {
            // custom wrapper Class.
            type: String,
            required: false,
        },
        selectClass: {
            // custom Class.
            type: String,
            required: false,
        },
        selectAutocomplete: {
            // ["on", "off", "given-name", "additional-name", "family-name", "email", "new-password", "current-password", "street-address", "postal-code", ...].
            type: String,
            required: false,
        },
        selectAutofocus: {
            // Determine if have input focus when the page loads.
            type: Boolean,
            required: false,
        },
        selectDisabled: {
            // The Boolean disabled attribute, when present, makes the element not mutable, focusable, or even submitted with the form.
            type: Boolean,
            required: false,
            default: false,
        },
        selectForm: {
            // must match the id of a <form> element with which the input is associated.
            type: String,
            required: false,
        },
        selectName: {
            // Name of the form control. Submitted with the form as part of a name/value pair.
            type: String,
            required: true,
        },
        selectMultiple: {
            // Boolean. Whether to allow multiple options can be selected in the list.
            type: Boolean,
            required: false,
        },
        selectRequired: {
            // The Boolean required attribute, if present, indicates that the user must specify a value for the input before the owning form can be submitted.
            type: Boolean,
            required: false,
            default: false,
        },
        selectSize: {
            // the number of rows in the list that should be visible at one time.
            type: Number,
            required: false,
        },
        selectOptions: {
            // Array of <option>. Option object has keys: label, value, disabled, selected.
            type: Array as PropType<Option[]>,
            required: false,
        },
        selectOptionsGroup: {
            // Array of <optgroup>. Optgroup object has keys: label, disabled and Options array.
            type: Array as PropType<OptionGroup[]>,
            required: false,
        },
        selectValue: {
            // The initial value of the control.
            type: String,
            required: false,
        },
        selectLabel: {
            // text for the <label> element.
            type: String,
            required: true,
        },
    },
});
</script>
