// .assets/vue/components/BasicFieldset.vue
<template v-if="fieldsetInputs && ['checkbox', 'radio'].includes(fieldsetType)">
    <fieldset
        :class="fieldsetClass"
        :disabled="fieldsetDisabled"
        :form="fieldsetForm"
        :name="fieldsetName"
    >
        <legend :class="fieldsetLegendClass" v-html="fieldsetLegend" />
        <BasicInput
            v-for="(input, index) of fieldsetInputs"
            :key="index"
            inputWrapperClass="label-after"
            :inputType="fieldsetType"
            :inputId="typeof input.id === 'undefined' ? input.value : input.id"
            :inputName="fieldsetName"
            :inputForm="fieldsetForm"
            :inputLabel="input.label"
            :inputDisabled="input.disabled"
            :inputChecked="input.checked"
            :inputRequired="input.required"
            :inputValue="input.value"
        />
    </fieldset>
</template>

<script lang="ts">
import { type PropType, defineComponent } from "vue";
import BasicInput from "./BasicInput.vue";

interface Input {
    label: string;
    value: string;
    id?: string;
    disabled?: boolean;
    checked?: boolean;
    required?: boolean;
}

export default defineComponent({
    name: "BasicFieldset",
    components: { BasicInput },
    props: {
        fieldsetClass: {
            // custom Class.
            type: String,
            required: false,
        },
        fieldsetLegendClass: {
            // custom Class.
            type: String,
            required: false,
        },
        fieldsetForm: {
            type: String,
        },
        fieldsetName: {
            type: String,
        },
        fieldsetDisabled: {
            type: Boolean,
        },
        fieldsetLegend: {
            type: String,
        },
        fieldsetType: {
            type: String,
        },
        fieldsetInputs: {
            // Array of <inputs>. Input object has keys: label, value, disabled, selected.
            type: Array as PropType<Input[]>,
            required: true,
        },
    },
});
</script>

// .assets/angular/components/BasicFieldset/BasicFieldset.component.ts
import { Component, Input, booleanAttribute, } from '@angular/core';
import { BasicInputComponent } from '../BasicInput/BasicInput.component';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  standalone: true,
  selector: 'app-basic-fieldset',
  imports: [FormsModule, CommonModule, BasicInputComponent],
  templateUrl: './BasicFieldset.component.html',
  styleUrl: './BasicFieldset.component.scss'
})
export class BasicFieldsetComponent {
  @Input() fieldsetClass: string = '';
  @Input() fieldsetLegendClass: string = '';
  @Input() fieldsetLegend: string = '';
  @Input({ transform: booleanAttribute }) fieldsetDisabled: boolean = false;
  @Input() fieldsetForm: string = '';
  @Input() fieldsetName: string = '';
  @Input() fieldsetType: string = 'radio';

  @Input({ transform: parseIt }) fieldsetInputs: InputObj[] = [];
}

interface InputObj {
  label: string;
  value: string;
  id?: string;
  disabled?: boolean;
  checked?: boolean;
  required?: boolean;
}

function parseIt(object: string): InputObj[] {
  return JSON.parse(object)
}

<fieldset
    *ngIf="fieldsetInputs && ['checkbox', 'radio'].includes(fieldsetType)"
    class="{{ fieldsetClass }}"
    disabled="{{ fieldsetDisabled ? 'disabled' : null }}"
    [attr.form]="fieldsetForm"
    name="{{ fieldsetName }}"
    >
    <legend class="{{ fieldsetLegendClass }}"
        [innerHTML]="fieldsetLegend"></legend>
    <app-basic-input
        *ngFor="let input of fieldsetInputs"
        inputType="{{ fieldsetType }}"
        inputId="{{ input.id ? input.id : input.value }}"
        inputName="{{ fieldsetName }}"
        inputForm="{{ fieldsetForm }}"
        inputLabel="{{ input.label }}"
        inputDisabled="{{ input.disabled === true ? 'disabled' : false }}"
        inputChecked="{{ input.checked }}"
        inputRequired="{{ input.required }}"
        inputValue="{{ input.value }}"
        inputWrapperClass="wrapper-custom-css"
        inputLabelClass="label-custom-css"
        inputClass="my-css-class"
        [(ngModel)]="input.value"
    ></app-basic-input>
</fieldset>
